language: cpp
compiler:
- gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl-* libglm-dev libboost-all-dev

branches:
  only:
    - master

notifications:
  email: true

# before build script, run autoreconf
before_script: autoreconf -i

os:
- linux
- osx

sudo: true